import { MainNav } from '@/components/main-nav';
import Sidebar from '@/components/sidebar';
import { Toaster } from '@/components/ui/toaster';
import AuthProvider from '@/providers/authProvider';
import { ThemeProvider } from '@/providers/themeProvider';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import ReduxProvider from '../redux/provider';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Sphiria Digita Studio | EMS',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={`${inter.className} overflow-hidden`}>
        {/* <SocketProvider> */}
        <ThemeProvider attribute='class' defaultTheme='system' enableSystem>
          <AuthProvider>
            <ReduxProvider>
              <div className='flex h-screen overflow-hidden  bg-[#eef5f9] dark:bg-slate-800'>
                <Sidebar />
                <div className='container flex flex-col w-full overflow-x-hidden'>
                  <MainNav />
                  <div className='flex-grow overflow-x-auto overflow-y-auto '>
                    {children}
                  </div>
                </div>
              </div>
              <Toaster />
            </ReduxProvider>
          </AuthProvider>
        </ThemeProvider>
        {/* </SocketProvider> */}
      </body>
    </html>
  );
}
